name: Keep Alive Planif Runbooster

on:
  schedule:
    - cron: "0 */10 * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update timestamp in .keepalive file
        run: |
          echo "Last ping: $(date -u)" > .keepalive
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .keepalive
          git commit -m "Keep alive ping at $(date -u)"
          git push origin main
